openapi: 3.0.0
info:
  title: API de Citas Médicas - ms-appointment
  description: Documentación de endpoints para gestión de citas médicas.
  version: 1.0.0

servers:
  - url: https://5codsuh7ie.execute-api.us-east-1.amazonaws.com/dev
    description: AWS Dev

tags:
  - name: Appointments
    description: Endpoints para gestión de citas médicas

paths:
  /appointments/create:
    post:
      tags:
        - Appointments
      summary: Crear una nueva cita médica (versión inicial)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                insuredId:
                  type: string
                  example: PE02193878293
                scheduleId:
                  type: integer
                  example: 101
                countryISO:
                  type: string
                  example: PE
                centerId:
                  type: integer
                  example: 12
                specialtyId:
                  type: integer
                  example: 5
                medicId:
                  type: integer
                  example: 99
                date:
                  type: string
                  format: date-time
                  example: "2025-05-05T10:30:00Z"
              required:
                - insuredId
                - scheduleId
                - countryISO
                - centerId
                - specialtyId
                - medicId
                - date
      responses:
        '202':
          description: Cita creada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Agendamiento en proceso
                  data:
                    type: object
                    properties:
                      insuredId:
                        type: string
                        example: PE02193878293
                      scheduleId:
                        type: integer
                        example: 101
                      countryISO:
                        type: string
                        example: PE
                      centerId:
                        type: integer
                        example: 12
                      specialtyId:
                        type: integer
                        example: 5
                      medicId:
                        type: integer
                        example: 99
                      date:
                        type: string
                        format: date-time
                        example: "2025-05-05T10:30:00Z"
                      status:
                        type: string
                        example: pending
                      createdAt:
                        type: string
                        format: date-time
                        example: "2025-05-04T00:57:57.564Z"

  /appointments:
    get:
      tags:
        - Appointments
      summary: Obtener listado de citas médicas
      responses:
        '200':
          description: Lista de citas obtenida exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Appointments recuperados exitosamente
                  count:
                    type: integer
                    example: 5
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        insuredId:
                          type: string
                          example: CHILECODE0001
                        date:
                          type: string
                          format: date-time
                          example: "2025-05-05T10:30:00Z"
                        scheduleId:
                          type: integer
                          example: 101
                        centerId:
                          type: integer
                          example: 12
                        medicId:
                          type: integer
                          example: 99
                        status:
                          type: string
                          example: pending
                        specialtyId:
                          type: integer
                          example: 1
                        createdAt:
                          type: string
                          format: date-time
                          example: "2025-05-04T00:18:13.872Z"
                        countryISO:
                          type: string
                          example: PE
